services:
  ai:
    build:
      context: .
    container_name: ssiren-ai
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - ssiren-network

networks:
  ssiren-network:
    external: true
    name: ssiren-network
